lab4-2: main.o src/Triangle.o src/Circle.o src/Rectangle.o src/Figure.o 
	g++ main.o src/Figure.o src/Rectangle.o src/Circle.o src/Triangle.o -o lab4-2

main.o: main.cpp src/Figure.hpp src/Circle.hpp src/Triangle.hpp src/Rectangle.hpp
	g++ -c main.cpp
